// In a real application, these would be API calls to your Django backend.
// For example, using axios:
// import axios from 'axios';
// export const fetchRankings = () => axios.get('/api/v1/rankings/');
// export const fetchQuestions = () => axios.get('/api/v1/questions/');

export const mockQuestions = [
    { id: 1, category: 'Website Strength', text: 'Is your website traffic encrypted using a valid and current SSL/TLS certificate (HTTPS)?', options: ['Yes, on all pages, with HSTS enabled', 'Yes, standard certificate on all pages', 'Only on sensitive pages', 'Certificate is expired/misconfigured', 'No, we use HTTP only'] },
    { id: 2, category: 'Website Strength', text: 'How often are your website\'s software components (CMS, plugins) updated?', options: ['Automatically within 48 hours', 'Weekly', 'Sporadically', 'Rarely or never', 'I don\'t know'] },
    { id: 3, category: 'Website Strength', text: 'Placeholder Q3', options: ['A', 'B', 'C', 'D', 'E']}, { id: 4, category: 'Website Strength', text: 'Placeholder Q4', options: ['A', 'B', 'C', 'D', 'E']}, { id: 5, category: 'Website Strength', text: 'Placeholder Q5', options: ['A', 'B', 'C', 'D', 'E']}, { id: 6, category: 'Website Strength', text: 'Placeholder Q6', options: ['A', 'B', 'C', 'D', 'E']}, { id: 7, category: 'Website Strength', text: 'Placeholder Q7', options: ['A', 'B', 'C', 'D', 'E']},
    { id: 4, category: 'Devices & Network', text: 'Do you maintain an up-to-date inventory of all devices on your network?', options: ['Yes, automated real-time inventory', 'Yes, a manual spreadsheet', 'Partial or outdated inventory', 'I don\'t know', 'No inventory'] },
    { id: 5, category: 'Devices & Network', text: 'Is a firewall configured to block unsolicited incoming traffic?', options: ['Yes, dedicated hardware firewall', 'Yes, software firewalls on endpoints', 'Only the default router firewall', 'Firewall is disabled', 'I don\'t know'] },
    { id: 6, category: 'Compliance Documentation', text: 'Do you have a formally documented Information Security Policy?', options: ['Yes, reviewed annually and trained on', 'Yes, a documented policy exists', 'Informal or outdated version', 'I don\'t know', 'No'] },
    { id: 7, category: 'Compliance Documentation', text: 'Are your data handling practices compliant with relevant regulations?', options: ['Yes, formally audited', 'We believe we are compliant', 'Aware but no formal steps taken', 'Not aware of regulations', 'I don\'t know'] },
    { id: 8, category: 'Website Strength', text: 'Have you implemented security headers like CSP?', options: ['Yes, a strong CSP', 'Yes, basic headers', 'Aware but not implemented', 'What are security headers?', 'No'] },
    { id: 9, category: 'Devices & Network', text: 'Do you maintain an up-to-date inventory of all devices on your network?', options: ['Yes, automated real-time inventory', 'Yes, a manual spreadsheet', 'Partial or outdated inventory', 'I don\'t know', 'No inventory'] },
    { id: 10, category: 'Devices & Network', text: 'Placeholder Q10', options: ['A', 'B', 'C', 'D', 'E']}, { id: 11, category: 'Devices & Network', text: 'Placeholder Q11', options: ['A', 'B', 'C', 'D', 'E']}, { id: 12, category: 'Devices & Network', text: 'Placeholder Q12', options: ['A', 'B', 'C', 'D', 'E']}, { id: 13, category: 'Devices & Network', text: 'Placeholder Q13', options: ['A', 'B', 'C', 'D', 'E']}, { id: 14, category: 'Devices & Network', text: 'Placeholder Q14', options: ['A', 'B', 'C', 'D', 'E']},
    { id: 15, category: 'Devices & Network', text: 'Is a firewall configured to block unsolicited incoming traffic?', options: ['Yes, dedicated hardware firewall', 'Yes, software firewalls on endpoints', 'Only the default router firewall', 'Firewall is disabled', 'I don\'t know'] },
    { id: 16, category: 'Compliance Documentation', text: 'Do you have a formally documented Information Security Policy?', options: ['Yes, reviewed annually and trained on', 'Yes, a documented policy exists', 'Informal or outdated version', 'I don\'t know', 'No'] },
    { id: 17, category: 'Compliance Documentation', text: 'Placeholder Q17', options: ['A', 'B', 'C', 'D', 'E']}, { id: 18, category: 'Compliance Documentation', text: 'Placeholder Q18', options: ['A', 'B', 'C', 'D', 'E']}, { id: 19, 'category': 'Compliance Documentation', text: 'Placeholder Q19', options: ['A', 'B', 'C', 'D', 'E']}, { id: 20, category: 'Compliance Documentation', text: 'Placeholder Q20', options: ['A', 'B', 'C', 'D', 'E']},
    { id: 21, category: 'Compliance Documentation', text: 'Are your data handling practices compliant with relevant regulations?', options: ['Yes, formally audited', 'We believe we are compliant', 'Aware but no formal steps taken', 'Not aware of regulations', 'I don\'t know'] },
    { id: 22, category: 'Cyber Security Implementations', text: 'Do you use an Intrusion Detection/Prevention System (IDS/IPS)?', options: ['Yes, managed and monitored', 'Yes, a device is running', 'Planning to implement', 'What is an IDS/IPS?', 'No'] },
    { id: 23, category: 'Cyber Security Implementations', text: 'Placeholder Q23', options: ['A', 'B', 'C', 'D', 'E']}, { id: 24, category: 'Cyber Security Implementations', text: 'Placeholder Q24', options: ['A', 'B', 'C', 'D', 'E']}, { id: 25, category: 'Cyber Security Implementations', text: 'Placeholder Q25', options: ['A', 'B', 'C', 'D', 'E']}, { id: 26, category: 'Cyber Security Implementations', text: 'Placeholder Q26', options: ['A', 'B', 'C', 'D', 'E']}, { id: 27, category: 'Cyber Security Implementations', text: 'Placeholder Q27', options: ['A', 'B', 'C', 'D', 'E']}, { id: 28, category: 'Cyber Security Implementations', text: 'Placeholder Q28', options: ['A', 'B', 'C', 'D', 'E']}, { id: 29, category: 'Cyber Security Implementations', text: 'Placeholder Q29', options: ['A', 'B', 'C', 'D', 'E']},
    { id: 30, category: 'Cyber Security Implementations', text: 'Is access to sensitive data restricted based on the principle of least privilege?', options: ['Yes, strictly controlled and reviewed', 'Yes, basic roles exist', 'Access granted but rarely revoked', 'Most employees have access to most data', 'I don\'t know'] }
];

export const mockRankings = [
    { rank: 1, name: 'Innovate UK Ltd.', score: 89, location: 'London', type: 'FinTech', lat: 51.5074, lng: -0.1278, report: { overall: 89, ws: 95, dn: 85, cd: 80, cs: 92 } },
    { rank: 2, name: 'Manchester Tech Co.', score: 85, location: 'Manchester', type: 'SaaS', lat: 53.4808, lng: -2.2426, report: { overall: 85, ws: 90, dn: 88, cd: 75, cs: 82 } },
    { rank: 3, name: 'Bristol Digital Agency', score: 82, location: 'Bristol', type: 'Marketing', lat: 51.4545, lng: -2.5879, report: { overall: 82, ws: 85, dn: 80, cd: 88, cs: 79 } },
    { rank: 4, name: 'Cambridge AI Solutions', score: 79, location: 'Cambridge', type: 'AI/ML', lat: 52.2053, lng: 0.1218, report: { overall: 79, ws: 75, dn: 85, cd: 82, cs: 78 } },
    { rank: 5, name: 'Secure Hosting UK', score: 78, location: 'London', type: 'IT Services', lat: 51.515, lng: -0.09, report: { overall: 78, ws: 88, dn: 70, cd: 75, cs: 80 } },
    { rank: 6, name: 'Birmingham Logistics', score: 75, location: 'Birmingham', type: 'Logistics', lat: 52.4862, lng: -1.8904, report: { overall: 75, ws: 70, dn: 78, cd: 80, cs: 72 } },
    { rank: 7, name: 'Leeds E-commerce', score: 71, location: 'Leeds', type: 'E-commerce', lat: 53.8008, lng: -1.5491, report: { overall: 71, ws: 78, dn: 65, cd: 70, cs: 70 } },
    { rank: 8, name: 'Oxford EduTech', score: 68, location: 'Oxford', type: 'Education', lat: 51.7520, lng: -1.2577, report: { overall: 68, ws: 65, dn: 72, cd: 60, cs: 75 } },
    { rank: 9, name: 'Glasgow Creative', score: 65, location: 'Glasgow', type: 'Creative', lat: 55.8642, lng: -4.2518, report: { overall: 65, ws: 72, dn: 60, cd: 68, cs: 61 } },
    { rank: 10, name: 'Data Insights London', score: 64, location: 'London', type: 'Data Analytics', lat: 51.512, lng: -0.13, report: { overall: 64, ws: 60, dn: 68, cd: 65, cs: 63 } },
    { rank: 11, name: 'Cardiff Solutions', score: 62, location: 'Cardiff', type: 'IT Services', lat: 51.4816, lng: -3.1791, report: { overall: 62, ws: 68, dn: 65, cd: 55, cs: 60 } },
    { rank: 12, name: 'Edinburgh Consulting', score: 60, location: 'Edinburgh', type: 'Consulting', lat: 55.9533, lng: -3.1883, report: { overall: 60, ws: 55, dn: 62, cd: 65, cs: 58 } },
    { rank: 13, name: 'Liverpool Retail', score: 58, location: 'Liverpool', type: 'Retail', lat: 53.4084, lng: -2.9916, report: { overall: 58, ws: 62, dn: 55, cd: 50, cs: 65 } },
    { rank: 14, name: 'Nottingham Gaming', score: 55, location: 'Nottingham', type: 'Gaming', lat: 52.9548, lng: -1.1581, report: { overall: 55, ws: 50, dn: 60, cd: 58, cs: 52 } },
    { rank: 15, name: 'Sheffield Manufacturing', score: 52, location: 'Sheffield', type: 'Manufacturing', lat: 53.3811, lng: -1.4701, report: { overall: 52, ws: 45, dn: 58, cd: 55, cs: 50 } },
    { rank: 16, name: 'Newcastle Health', score: 49, location: 'Newcastle', type: 'Healthcare', lat: 54.9783, lng: -1.6178, report: { overall: 49, ws: 52, dn: 50, cd: 45, cs: 49 } },
    { rank: 17, name: 'Aberdeen Energy', score: 45, location: 'Aberdeen', type: 'Energy', lat: 57.1497, lng: -2.0943, report: { overall: 45, ws: 40, dn: 55, cd: 40, cs: 45 } },
    { rank: 18, name: 'Belfast Logistics', score: 42, location: 'Belfast', type: 'Logistics', lat: 54.5973, lng: -5.9301, report: { overall: 42, ws: 48, dn: 40, cd: 35, cs: 45 } },
    { rank: 19, name: 'Southampton Marine', score: 38, location: 'Southampton', type: 'Marine', lat: 50.9097, lng: -1.4044, report: { overall: 38, ws: 35, dn: 45, cd: 40, cs: 32 } },
    { rank: 20, name: 'Plymouth Construction', score: 35, location: 'Plymouth', type: 'Construction', lat: 50.3755, lng: -4.1427, report: { overall: 35, ws: 30, dn: 40, cd: 38, cs: 32 } },
];
